### ISSUE TITLE
Add nuget-license check into sonar

### ISSUE THREAD

**Issue by bheemreddy181** [tomchavakis/nuget-license#106]
Can we add support for incorporating nuget-license into https://github.com/porscheinformatik/sonarqube-licensecheck so that it runs along with other license checks ?

**Comment by sensslen** [comment]
I don't see anything that prevents you from doing so. The Project is even published under a very permissive license, so if any modifications are needed, you are free to go ahead. From my experience PR's are highly welcome to this project.

**Comment by tomchavakis** [comment]
Hi @bheemreddy181,

Yes, you are more than welcome to contribute to the project as @sensslen mentioned.
If you need anything regarding the implementation please let us know.

**Comment by bheemreddy181** [comment]
Hey @tomchavakis @sensslen can you help with implementation atleast the steps to perform this ?

**Comment by sensslen** [comment]
To be completely honest, I guess you‘re starting at the wrong end. To integrate with the project you mention, you must first get to know it‘s api. Once you know that, we can start looking into solutions on how to provide the needed data. For this step I might be able to provide assistance. Please follow up on this ticket once you were able to figure out how sonarcube requests data and in which format it needs the response.

**Comment by sensslen** [comment]
Closing this as a stale issue
