### ISSUE TITLE
Multiple NuGet Source Support

### ISSUE THREAD

**Issue by ohanedan** [tomchavakis/nuget-license#117]
Hello,
Can we use multiple nuget sources? It looks check only api.nuget.org but I have also a private repository for my packages. Do you think about any improvement for this? 
Thanks

**Comment by sensslen** [comment]
There is a branch for version 3.0.0 (be aware that this branch is still a prerelease) which uses the microsoft provided capabilities to receive the nuget packages. With this branch the feature you describe works.

Feel free to check this out.

**Comment by ohanedan** [comment]
Hi @sensslen,
Thanks for quick response,
Do you plan to push version 3.0.0 to nuget as a prerelease for testing with "dotnet tool install" command easily?

**Comment by sensslen** [comment]
@tomchavakis what do you think?

**Comment by sensslen** [comment]
I propose to close this issue in favour of the newly released alpha version that will eventually replace the current version of the application. Please check https://github.com/tomchavakis/nuget-license/releases/tag/v3.0.0-alpha.5 if it will fit your needs.

The newly released alpha version is also available as dotnet tool.
