### ISSUE TITLE
Do not crash on .NET Framework projects

### ISSUE THREAD

**Issue by s-rech** [tomchavakis/nuget-license#15]
I guess the intention of the tool is to only support .NET Core and .NET Standard projects (even though the project description does not state so explicitly).
However, it might be better if the tool does not crash if one of the included projects is a .NET Framework project. Instead, this type of project could simply be ignored (with a warning).

The crash happens in `Methods.GetProjectReferences`, because element "Project" is not available in project file of a .NET Framework project.

**Comment by mersadk** [comment]
This should work now, it's solved with #17 pull request.

**Comment by MKuckert** [comment]
Closing for now as this should be supported now. Feel free to reopen or create a new issue in case of additional input
