### ISSUE TITLE
Possibility of showing Dependency graph?

### ISSUE THREAD

**Issue by rohitcoder** [tomchavakis/nuget-license#159]
I just wanted to check, if there is any possibility for this tool to Show a dependency graph (showing all children of dependencies)

I tried `` dotnet list /folder/ package --include-transitive``  but this doesn't show a relation graph

**Comment by sensslen** [comment]
While this could be implemented for sure, I don‘t see this as one of the responsibilities of this tool. It does list and validate licenses. It has nothing to do with dependency graphs. The crawling of dependencies is just a necessary inconvenience for this tool. Why not request this feature from the dotnet/nuget tools?
