### ISSUE TITLE
Wrong licence output

### ISSUE THREAD

**Issue by OwnageIsMagic** [tomchavakis/nuget-license#165]
Tool outputs following result, but ASP Net **Core** is MIT licensed.
https://www.nuget.org/packages/Microsoft.AspNetCore.Authorization
https://github.com/dotnet/aspnetcore/blob/main/LICENSE.txt
```
####################################################################################################
Package:Microsoft.AspNetCore.Authentication.Abstractions
Version:2.0.0
project URL:https://asp.net/
Description:ASP.NET Core common types used by the various authentication components.
licenseUrl:https://raw.githubusercontent.com/aspnet/Home/2.0.0/LICENSE.txt
license Type:Apache-2.0
```
Seems like it wrongly resolves to ASP MVC 6

**Comment by svenclaesson** [comment]
You can see here that this package is Apache-2.0 (click License info in right menu)
https://www.nuget.org/packages/Microsoft.AspNetCore.Authentication.Abstractions/2.0.0

**Comment by OwnageIsMagic** [comment]
Yes, I'm sorry
