### ISSUE TITLE
Add support for .NET7

### ISSUE THREAD

**Issue by magsto** [tomchavakis/nuget-license#168]
The nuget doesn't support .NET7 when added to an Azure DevOps build pipeline.

This is the output when using SDK .NET 7.0.100

```
You can invoke the tool using the following command: dotnet-project-licenses
Tool 'dotnet-project-licenses' (version '2.4.0') was successfully installed.
You must install or update .NET to run this application.

App: /home/vsts/.dotnet/tools/dotnet-project-licenses
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /opt/hostedtoolcache/dotnet

The following frameworks were found:
  7.0.0 at [/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by sensslen** [comment]
Please consider using the 3.0.0-alpha version. It will be released with .net7 support once #172 is merged. This version is still under active development so the command line output/options might still change (however I do not expect this to happen). This version will eventually replace the 2.x version and provides a numer of improvemnts. Most noticable: It uses Microsoft provided mechanisms to determine the referenced packages so It's safe to expect it to print the same dependencies as dotnet itself.

**Comment by tomchavakis** [comment]
@magsto,
The .net7 has been added to the project.  (https://github.com/tomchavakis/nuget-license/pull/177)
Please use the following command if you want to install the tool in this specific version.
dotnet tool install --global dotnet-project-licenses --version 2.5.0
