### ISSUE TITLE
Version `100.100.100` was released on nuget.org

### ISSUE THREAD

**Issue by Setre14** [tomchavakis/nuget-license#173]
It seems like the version `100.100.100` was published to https://www.nuget.org/packages/dotnet-project-licenses, however this version does not work.

And since it also does not show up in the releases here on Github, I guess this version wasn't supposed to be released.

**Comment by benjaminfuchs** [comment]
Seems it was this one: https://github.com/tomchavakis/nuget-license/actions/runs/3531951976/jobs/5925710871

**Comment by svenclaesson** [comment]
@tomchavakis got the access to fix this. 🙏

**Comment by sensslen** [comment]
@felix-barz-brickmakers infortunately I cannot do this - I don‘t have the proper access rights…

**Comment by tomchavakis** [comment]
@sensslen this version has been deprecated and has been removed from the list. 
Let me know if you need anything else.

**Comment by txs-lars** [comment]
It is still listet here:

**Comment by sensslen** [comment]
According to https://learn.microsoft.com/en-us/nuget/nuget-org/policies/deleting-packages undistinguished seems to not be enough. @tomchavakis  could you contact Microsoft to remove this faulty package? I‘m very sorry for having uploaded this - there was an error in the automatic publish procedure…

In the mean time everybody could work around this by specifying a version range…

`dotnet tool install dotnet-project-licenses --version [desired version]`

**Comment by tomchavakis** [comment]
@sensslen, no reason to apologise. 
I have already sent a message to the nuget team to remove entirely this version from the list.
Thank you for pointing out the documentation.
@txs-lars, thanks for the endpoint info.

**Comment by tomchavakis** [comment]
@sensslen, @txs-lars, @Setre14 
Nuget has deleted this package.
