### ISSUE TITLE
Specify output folder/file

### ISSUE THREAD

**Issue by tomasbruckner** [tomchavakis/nuget-license#21]
Hi,

great tool, but it would be awesome if you could specify the output folder/file in `-o` option. I can send PR if you are busy.

**Comment by tomchavakis** [comment]
Hi tomas,

Thanks for your willing to support this tool.
You can send any PR you like, it is more than welcome!!!
I suppose that this functionality is already implemented using the following command.

`dotnet-project-licenses -i projectFolder -u -o`

What do you think ?

**Comment by MKuckert** [comment]
Additionally there's an `--outfile` option

**Comment by MKuckert** [comment]
Closing for now as there's already an option. Feel free to reopen or create a new issue in case of additional input
