### ISSUE TITLE
MSBuild variables not evaluated as part of the PackageReference

### ISSUE THREAD

**Issue by pableess** [tomchavakis/nuget-license#29]
csproj file allows the use of variables in the ProjectReference in the csproj file.  Variables can be set via Environment variables, command line parameters etc.

The tool does not evaluate these variables before querying the package information.

**Comment by tomchavakis** [comment]
Hi @pableess,

@jpeirson added a new flag to use project assets json. Can you check please if your need is covered in order to close this issue?

Thanks in advance

**Comment by sensslen** [comment]
I propose to close this issue in favour of the newly released alpha version that will eventually replace the current version of the application. Please check https://github.com/tomchavakis/nuget-license/releases/tag/v3.0.0-alpha.5 if it will fit your needs.
