### ISSUE TITLE
Transitive packages

### ISSUE THREAD

**Issue by orbus-dkreivenas** [tomchavakis/nuget-license#31]
Hello, it would be very useful to print out transitive package licenses as well. Is this something planned already?

**Comment by orbus-dkreivenas** [comment]
I have the change locally to do this. I could create a pull request if you like.

**Comment by MKuckert** [comment]
Merged your PR. Thank you 👍

**Comment by orbus-dkreivenas** [comment]
Will you release the new version ? :)

**Comment by tomchavakis** [comment]
> Will you release the new version ? :)

The version v2.2.1 released with your changes!!

**Comment by orbus-dkreivenas** [comment]
Great, thank you!
