### ISSUE TITLE
NuGet local package cache: local packages not found on linux

### ISSUE THREAD

**Issue by alesebi91** [tomchavakis/nuget-license#70]
Issue when try to read package information inside local package cache on Linux.
Packages folder in Linux filesystem has lowercase package name:
_/root/.nuget/packages/microsoft.identitymodel.tokens_

**Comment by tomchavakis** [comment]
Hi @alesebi91,

Thank you for your contribution. Version v2.3.1 has been released. 

https://www.nuget.org/packages/dotnet-project-licenses/2.3.1
Please verify that your issue has been resolved and if everything is fine then you can also close the Issue.

**Comment by alesebi91** [comment]
Issue is resolved in version 2.3.1.
@tomchavakis: I proceed to close the issue.

Thank you!

**Comment by tomchavakis** [comment]
thank's @alesebi91
