### ISSUE TITLE
Target framework is not taken into account

### ISSUE THREAD

**Issue by ngyukman** [tomchavakis/nuget-license#80]
For example in https://api.nuget.org/v3-flatcontainer/ReactiveUI/13.2.2/ReactiveUI.nuspec

Different target has different dependencies, but most noticeable one is Tizen.Net in Tizen4.0, which brings wrong information into the report

as an alternatively, could the project use "dotnet list package --include-transitive" for getting the dependency list?

**Comment by sensslen** [comment]
I propose to close this issue in favour of the newly released alpha version that will eventually replace the current version of the application. Please check https://github.com/tomchavakis/nuget-license/releases/tag/v3.0.0-alpha.5 if it will fit your needs.
