### ISSUE TITLE
No result for dotnet-project-licenses

### ISSUE THREAD

**Issue by aminkosh** [tomchavakis/nuget-license#85]
Hi,

I execute the following command but nothing happens for me.
` dotnet-project-licenses -i c:\test --export-license-texts `
I see just "Project Reference(s) Analysis..." but without result.

Any help appreciated

**Comment by tomchavakis** [comment]
Hi @aminkosh,

The command is fine. 
Could you please share more information about the version you are using and if the test folder is a root folder of a .NET Solution ?

Thanks

**Comment by aminkosh** [comment]
Hi, 
the problem was about a security issue. 
I will close this.
Thanks a lot.
