### ISSUE TITLE
Support for the NUGET_PACKAGES environment variabele 

### ISSUE THREAD

**Issue by ValentijnMakkenze** [tomchavakis/nuget-license#88]
We use the NUGET_PACKAGES environment variabele to store the nuget packages somewhere else but now the tools doesn't find the packages and downloads them all again

**Comment by tomchavakis** [comment]
Hi @ValentijnMakkenze 

Currently, the tool doesn't support the NUGET_PACKAGES Environmental Variable. 
It's a new feature with a new option parameter.
If you want to implement this feature you are more than welcome.
Thanks for reporting this issue.

**Comment by tomchavakis** [comment]
The release of this feature occurred at the release v2.3.12
