### ISSUE TITLE
Support for .NET6

### ISSUE THREAD

**Issue by kl1mm** [tomchavakis/nuget-license#89]
Hi there,
would be cool to have your tool working with .NET6 

```
PS C:\...> dotnet-project-licenses -i . -u -o
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.0-rc.2.21480.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=win10-x64
```

Cheers, mMilk

**Comment by tomchavakis** [comment]
Hi @kl1mm ,

Thank you for this issue.
I've updated the project to support the .NET 6.0
This is the release:
https://github.com/tomchavakis/nuget-license/releases/tag/v2.3.6

**Comment by kl1mm** [comment]
Hi @tomchavakis,
thanks for your super fast response, i will try it out later today and let u know (close the issue)

Thank you  👍 

Cheers, mMilk
