### ISSUE TITLE
Support for Directory.Build.props

### ISSUE THREAD

**Issue by iduras3** [tomchavakis/nuget-license#93]
Packages defined in  Directory.Build.props are not evaluated during a license scan.

**Comment by sensslen** [comment]
I propose to close this issue in favour of the newly released alpha version that will eventually replace the current version of the application. Please check https://github.com/tomchavakis/nuget-license/releases/tag/v3.0.0-alpha.5 if it will fit your needs.

**Comment by galadril** [comment]
Any idea when this gets merged to the main version?
